
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
    creationTimestamp: null
    name: 1-clone-build-push
spec:
    params:
        - description: registry-domain/namespace where the output image should be pushed.
          name: image-registry-url
          type: string
    tasks:
        - name: clone-1
          params:
            - name: url
              value: git@github.com:rhdh-orchestrator-test/java-class-test
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: 1-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-1
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/sample-class
            - name: DOCKERFILE
              value: Dockerfile
            - name: CONTEXT
              value: .
          runAfter:
            - clone-1
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: 1-shared-data
            - name: dockerconfig
              workspace: registry-credentials
    workspaces:
        - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
          name: 1-shared-data
        - description: This workspace provides the credentials (Docker config.json) for pushing images to the registry. See https://hub.tekton.dev/tekton/task/kaniko
          name: registry-credentials
        - description: This workspace provides the credentials (ssh private key) for cloning the git repo. See https://hub.tekton.dev/tekton/task/git-clone
          name: git-ssh-credentials

...
