apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: flight-path-auto-tests-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  zzz_deprecatedclustername: ""
  managedfields: []
objects:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: sample-class
      name: sample-class
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: quay.io/test/sample-class:latest
              imagePullPolicy: Always
              name: sample-class
              ports:
                - containerPort: 8080
              resources: {}
          imagePullSecrets:
            - name: docker-credentials
          restartPolicy: Always
          securityContext: {}
    status: {}
parameters: []
